name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

#TODO: remove this after sources updates
model-paths: ["sources","models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
      materialized: materializedview
      #TODO: This is an important thing to figure out.
      #staging data is canonically just view definitions.
      #how can we test on those w/o materializing them?
      staging:
        materialized: materializedview

tests:
  jaffle_shop:
    +store_failures: true
    +schema: 'etl_failure'
